### ISSUE TITLE
III stage

### ISSUE THREAD

**Issue by rusdevops** [AnastasiaVern/VkClient#3]
@AnastasiaVern 

 - [x] 1. Отсутствует проверка корректного состояния стандартного потока ввода. [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/examples/main.cpp#L13).
 - [x] 2. Отсутствует проверка возвращаемого значения. [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/examples/main.cpp#L15).
 - [x] 3. Отсутствует пример запуска `Example`. [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/.travis.yml#L31).
 - [x] 4. Присутствуют избыточные комментарии. 
[здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/examples/main.cpp#L5), [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/examples/main.cpp#L16), [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/examples/main.cpp#L19), [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/sources/client.cpp#L98-99) и [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/sources/client.cpp#L102-L103).
 - [x] 5. Не корректная реализация ввода количества потоков. [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/examples/main.cpp#L18).
 - [x] 6. Не корректное именование локальной переменной. [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/sources/client.cpp#L120).
 - [x] 7. Отсутствует блок обработки невыполнения условия. [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/sources/client.cpp#L140) и [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/sources/client.cpp#L141).
 - [x] 8. Отсутствует обработка дополнительного флага `-v`. [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/sources/client.cpp#L136).
 - [x] 9. Присутствует избыточный код. [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/sources/client.cpp#L139).
 - [x] 10. Присутствует большой уровень вложенности. [здесь](https://github.com/AnastasiaVern/VkClient/blob/d0b710579d081144e5e258ea27a2c4b2b7ac1d57/sources/client.cpp#L119-L142).

**Comment by AnastasiaVern** [comment]
1. А что именно проверить? В чем предмет корректности?
2. OK
3. Так не получится, потому что Аccess token привязан к IP адрессу, с которого он получен
4. OK
5. OK
6. OK
7. OK 
8. OK
9. OK
10. OK

**Comment by rusdevops** [comment]
```
if (cin >> n) { 
  ... 
} 
else throw bad_argument(“...")  

<=>   

cin >> n; 
if (!cin) throw bad_argument(“…”); 
... 
```

**Comment by rusdevops** [comment]
Пришлите скриншоты работы `Example` вместо исправления пункта 3.

**Comment by AnastasiaVern** [comment]
1. OK
3.![image](https://cloud.githubusercontent.com/assets/17246088/20631725/41443600-b349-11e6-95d3-348e19fa25f6.png)

**Comment by rusdevops** [comment]
https://github.com/AnastasiaVern/VkClient/blob/master/examples/main.cpp#L17

**Comment by AnastasiaVern** [comment]
Ой
сейчас

**Comment by rusdevops** [comment]
@AnastasiaVern 

- [x] 1. Отсутствует проверка корректного состояния стандартного потока ввода. [здесь](https://github.com/AnastasiaVern/VkClient/blob/c2ae40428e37a6b195662b917d87049f3e4e3d4f/examples/main.cpp#L17).
- [x] 2. Отсутсвует блок обработки не выполнения условия. [здесь](https://github.com/AnastasiaVern/VkClient/blob/c2ae40428e37a6b195662b917d87049f3e4e3d4f/examples/main.cpp#L32).
- [x] 3. Отсутствует согласованность потоков для обработки ошибок. [здесь](https://github.com/AnastasiaVern/VkClient/blob/c2ae40428e37a6b195662b917d87049f3e4e3d4f/examples/main.cpp#L38) и [здесь](https://github.com/AnastasiaVern/VkClient/blob/c2ae40428e37a6b195662b917d87049f3e4e3d4f/sources/client.cpp#L144).
